### ISSUE TITLE
Feature request - commandline tool for accessing the adc values

### ISSUE THREAD

**Issue by jenswes** [FERCSA/FCDS#1]
Hi,
as the title said, i have a Feature request - commandline tool for accessing the adc values
this would be great for using the 32 channel ADC with scripts

thanks

**Comment by FERCSA** [comment]
Hi! 
Can you specify your system?
I guess you're using it under linux, right?

There is an example.c in this repo. Add the following at the end:
```
int main(int argc, char** argv){
	int data;
	data = read_ANA(argv[1], argv[2]);
	printf("CH%2d 0x%04X %04d\n", i, data, data);
	return 0;
}
```

Then `gcc example.c -o example && ./example 0x08 0`
First argument is your board's I2C address,  0x08.
Second argument is the channel number, 0.

**Comment by FERCSA** [comment]
Solved. Example.c updated on Sept. 4.
