### ISSUE TITLE
Issues with Example code for 32CH ADC

### ISSUE THREAD

**Issue by insignificantother** [FERCSA/FCDS#2]
Hey there,

I have one of your 32 channel ADC's. I have it hooked up to an arduino nano, but I can't for the life of me get your example code working. The board is recognized by the arduino through ic2 and there is definitely power to it but I can't get any readout from a sensor.

**Comment by FERCSA** [comment]
Hi! 
If the board recognized that's a good sign. I assume the i2c scanner found it, the address of the board is 0x08, right?
Can you provide the output of the example script? Did you make any modification on the code or it's the exactly same as on github?

Also can you tell me the date of purchase? So i can identify the board exactly.

**Comment by insignificantother** [comment]
Thanks for getting back so fast!

Yep the scanner found it at 0x08 so the address is right. I've tried using the exact same script as the github and modifying it a bit, but nothing either way. The made the order on July 16th. This is the output from the unmodified github code.

![screen shot 2018-11-08 at 9 29 32 am](https://user-images.githubusercontent.com/39780284/48216377-6e6bce00-e339-11e8-930b-626cbd3bba5c.png)

**Comment by FERCSA** [comment]
Firstly, modify these two lines:
https://github.com/FERCSA/FCDS/blob/master/SM_demo/example.ino#L48
https://github.com/FERCSA/FCDS/blob/master/SM_demo/example.ino#L51
Just change the zero values to something else (for example 11 and 22), so you can recognize them on the output. If you still got zeros the i2c communication is fine.

Do you have a multimeter?
Can you check your arduino's internal pull-ups are on? You should measure 3.3V on the SDA and SCL lines. Since your scanner found the board it should be okay.
Also check J10 on your module, it should be 3.3V either.

**Comment by insignificantother** [comment]
if I change the number on line 51 I receive that number in the readout.

I will have access to a multimeter later today to and can check the internal pull-ups.

**Comment by FERCSA** [comment]
Looks like it's a communication error.

Can you print out the data variable at line 41?
https://github.com/FERCSA/FCDS/blob/master/SM_demo/example.ino#L41
add this:
Serial.println(data, HEX);

**Comment by insignificantother** [comment]
This is the readout.

![screen shot 2018-11-08 at 12 15 48 pm](https://user-images.githubusercontent.com/39780284/48224985-60757780-e350-11e8-95bc-027a5c5bca3a.png)
![screen shot 2018-11-08 at 12 16 01 pm](https://user-images.githubusercontent.com/39780284/48224988-623f3b00-e350-11e8-918a-3c95d1f14389.png)
![screen shot 2018-11-08 at 12 16 15 pm](https://user-images.githubusercontent.com/39780284/48224990-6408fe80-e350-11e8-8b51-974b6e16bdf7.png)
![screen shot 2018-11-08 at 12 16 29 pm](https://user-images.githubusercontent.com/39780284/48225000-6703ef00-e350-11e8-8a53-d338bb760827.png)

**Comment by FERCSA** [comment]
I think I figured it out, it's a software issue in the example code.
Your module working just fine!

For example let's see channel 0:
You got a value of 130d9269, when we strip down the first and last byte, the result is:
0d92 which is 3474 in decimal. If you don't terminated this channel it should be okay.

Probably cause:
'data' variable, change line 41 to:
data = (data << 8) | (int)Wire.read();

One thing for sure the error is in the read_ANA() function.
Currently I can't test it on an atmel based board, sry. Usually I work with ESP32 and the example code is just running fine.

**Comment by insignificantother** [comment]
Same result if I change it. Not to worry. It's not the end of the world if I can't get it up and running.

**Comment by FERCSA** [comment]
This is the main problem:
https://www.arduino.cc/reference/en/language/variables/data-types/unsignedint/

Solution is simple, just change line 30 to
unsigned long data = 0x00;
https://github.com/FERCSA/FCDS/blob/master/SM_demo/example.ino#L30

**Comment by insignificantother** [comment]
and it's up and running! thank you so much!

**Comment by FERCSA** [comment]
Awesome!

Example.ino updated on Nov. 8.
