### ISSUE TITLE
Pin Tripple Readout Issue

### ISSUE THREAD

**Issue by Cibico99** [FERCSA/FCDS#3]
Hello,
 I am having an issue where using your example python code, I read out each pin 3 times. I then run your example code 3 times to get all 32 channels, is this a known issue?

In the attached example, i have pin 1 grounded out for each of the 4ch I/O Groups.

[pythonTripleReadout.txt](https://github.com/FERCSA/FCDS/files/5811600/pythonTripleReadout.txt)

**Comment by FERCSA** [comment]
Hi!
I think you have a I2C speed issue here. I got similar repeated readings just like you when there was a speed mismatch. Python's smbus/i2c handling is not so great.
Change the speed then it should be good. 

If you have any chance try out the C example to make sure the readings are working fine on your pi.

**Comment by FERCSA** [comment]
Inactivity. Probably solved.

**Comment by FERCSA** [comment]
Closed by inactivity. Probably solved.
